In [1]:
import numpy as np

In [2]:
import gym

In [3]:
import random

In [4]:
env = gym.make("FrozenLake-v0")

In [5]:
env

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>

In [7]:
env?

In [9]:
action_size = env.action_space.n

In [10]:
state_size = env.observation_space.n

In [11]:
print("action_size", action_size, "state_size", state_size)

action_size 4 state_size 16


In [12]:
qtable = np.zeros((state_size, action_size))

In [13]:
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
total_episodes = 15000
learning_rate = 0.8
max_steps = 99
gamma = 0.95
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [15]:
rewards = []
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0,1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards+=reward
        state = new_state
        if done == True:
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4746
[[1.61061730e-01 4.53248447e-02 1.27080158e-01 5.31402051e-02]
 [5.93779350e-03 2.06290131e-02 1.21489040e-02 3.97992696e-01]
 [1.11991938e-02 3.21204762e-01 3.58640315e-03 5.22207443e-02]
 [1.07497417e-02 9.11901741e-04 3.89953726e-03 1.18538336e-01]
 [2.14012728e-01 1.08037524e-04 2.59638449e-03 1.34963701e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.64411338e-02 5.25318431e-05 9.44168967e-05 3.01418935e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.03860822e-03 3.53139548e-03 4.84607379e-02 4.08109181e-01]
 [1.73923514e-02 7.50892530e-01 5.72716880e-02 9.28682749e-02]
 [2.72895467e-01 5.85612071e-05 3.81130630e-03 6.31147917e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.51322625e-02 1.09716477e-01 4.64233509e-01 1.12964904e-01]
 [1.57788214e-01 4.24124661e-01 2.19398924e-01 1.93168883e-01]
 [0.00000000e+00 0.00000000e+00

In [16]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 73
****************************************************
EPISODE  1
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 89
****************************************************
EPISODE  2
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 35
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 63
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 47


In [ ]:
SFFF       (S: starting point, safe)
FHFH       (F: frozen surface, safe)
FFFH       (H: hole, fall to your doom)
HFFG       (G: goal, where the frisbee is located)