In [1]:
import numpy as np
import matplotlib.pyplot as plt
raw_data_X = [
    [3.39, 2.33],
    [3.11, 1.78],
    [1.34, 3.36],
    [3.58, 4.67],
    [2.28, 2.86],
    [7.42, 4.69],
    [5.74, 3.53],
    [9.17, 2.51],
    [7.79, 3.42],
    [7.93, 0.79]
]

raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.09, 3.36])


In [2]:
%run 02_kNN_in_scikitlearn.py

In [3]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y

1

![what'sml](whatsml.png)

那么可以看出来kNN实际上是没有模型的.
但是相对来说<font color="red">训练集就是模型</font>

# scikit learn 中的knn


In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [6]:
kNN_classifier.fit?

In [7]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [8]:
kNN_classifier.predict(x.reshape(1,-1))

array([1])

In [9]:
X_predict = x.reshape(1, -1)

In [10]:
X_predict

array([[8.09, 3.36]])

In [11]:
y_predict = kNN_classifier.predict(X_predict)

In [12]:
y_predict

array([1])

## 重新整理我们自己的代码

In [13]:
%run playML/kNN.py

In [14]:
knn_clf = KNNClassifier(k=6)

In [15]:
knn_clf.fit(X_train, y_train)

KNN6

In [16]:
knn_clf.predict(X_predict)

array([1])