# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train test split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 方式1 生成测试数据

In [7]:
# 可以将他们合在一起后拆分方式1
all_combined = np.column_stack((X, y))

In [8]:
print("before shuffle")
print(all_combined)
np.random.shuffle(all_combined)
print("after shuffle")
print(all_combined)
# select test ratio
X_train_method1 = all_combined[:100,:3]
print("x train:")
print(X_train_method1)

before shuffle
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0


## 方式2 生成测试数据

In [9]:
# 生成一个随机排列
shuffle_indexs = np.random.permutation(len(X))

In [10]:
shuffle_indexs

array([ 95, 103,  99,  40, 100, 120,  47,  10,  64,   3,  37,  61,  30,
        19,  39,  43,  36,  86, 102, 119,  59, 131,  73,  93,  44, 111,
        57, 116, 112,   7,  69,  14, 123,   8,  76, 117,  77,  27, 109,
       146, 143,  97, 121,   1,  42,  53,  94,  60,  87,  65,   4,  68,
        32, 138, 139,  20, 130,   6,  51,  28,  21,  85, 122, 124, 115,
        33,  80,  83,  50,  89,  38,  84, 149, 129, 101, 127,  82,  26,
       147, 118,  54, 128, 140,  24, 107,  72, 134,  71,  81,  98, 125,
        88, 106,  11,  90, 137,  41,  18,  79, 145,  75,  29,  45, 135,
        13,   5,  56,  52, 108, 126,  22, 110,  16,  48,  49,   2,  46,
        78,  91, 142, 148,  66, 133,  70,  34,  55,  74, 104, 105,  23,
         0,  62,  31,  63,  17,  15, 136,  92,  25,  12,  96, 113,  67,
       132, 144,  35,   9, 141, 114,  58])

In [11]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [12]:
test_indexes = shuffle_indexs[:test_size]

In [13]:
train_indexes = shuffle_indexs[test_size:]

In [14]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [15]:
X_train.shape

(120, 4)

# 使用我们的算法

In [16]:
from playML.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [18]:
from playML.kNN import KNNClassifier
my_knn_clf = KNNClassifier(k = 3)

In [19]:
my_knn_clf.fit(X_train, y_train)

KNN3

In [23]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2,
       2, 1, 1, 0, 1, 0, 1, 2])

In [21]:
y_test

array([0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 1, 0, 1, 2])

In [24]:
sum(y_predict == y_test)

29

In [25]:
correct_rate = sum(y_predict == y_test)/len(y_test)
correct_rate

0.9666666666666667

## scikitlearn 中的train test split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [28]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
from sklearn.neighbors import KNeighborsClassifier