In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [3]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [4]:
print(digits.DESCR)

Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is a

In [5]:
X = digits.data

In [6]:
X.shape

(1797, 64)

In [7]:
y = digits.target

In [8]:
y.shape

(1797,)

In [9]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y[:30]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
X[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [12]:
somedigit = X[666]

In [13]:
somedigit

array([ 0.,  0.,  5., 15., 14.,  3.,  0.,  0.,  0.,  0., 13., 15.,  9.,
       15.,  2.,  0.,  0.,  4., 16., 12.,  0., 10.,  6.,  0.,  0.,  8.,
       16.,  9.,  0.,  8., 10.,  0.,  0.,  7., 15.,  5.,  0., 12., 11.,
        0.,  0.,  7., 13.,  0.,  5., 16.,  6.,  0.,  0.,  0., 16., 12.,
       15., 13.,  1.,  0.,  0.,  0.,  6., 16., 12.,  2.,  0.,  0.])

In [14]:
y[666]

0

In [15]:
some_digit_image = somedigit.reshape(8,8)
plt.imshow(some_digit_image, cmap = matplotlib.cm.binary)
plt.show()

In [16]:
from playML.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_ratio=0.2)

In [18]:
from playML.kNN import KNNClassifier

In [19]:
my_knn_clf = KNNClassifier(k=3)

In [20]:
my_knn_clf.fit(X_train, y_train)

KNN3

In [21]:
y_predict = my_knn_clf.predict(X_test)

In [22]:
y_predict

array([3, 5, 7, 1, 9, 0, 7, 1, 0, 3, 7, 8, 7, 8, 0, 8, 5, 9, 1, 6, 3, 6,
       2, 9, 7, 6, 7, 5, 1, 5, 2, 3, 1, 5, 0, 0, 4, 5, 2, 3, 4, 9, 3, 7,
       7, 3, 5, 1, 3, 4, 5, 8, 3, 1, 2, 4, 6, 6, 9, 7, 3, 7, 6, 9, 0, 4,
       9, 1, 6, 4, 5, 1, 8, 1, 3, 0, 1, 1, 6, 9, 3, 9, 9, 1, 9, 1, 3, 2,
       8, 6, 6, 4, 2, 1, 0, 7, 5, 4, 1, 8, 9, 4, 9, 2, 0, 1, 7, 3, 1, 3,
       5, 3, 1, 5, 2, 7, 3, 0, 3, 8, 7, 4, 1, 7, 5, 7, 7, 8, 6, 8, 4, 8,
       9, 0, 2, 9, 5, 9, 1, 2, 7, 1, 3, 6, 2, 3, 1, 5, 7, 3, 7, 2, 3, 8,
       6, 1, 9, 0, 3, 5, 0, 5, 4, 8, 8, 9, 6, 0, 1, 2, 6, 8, 2, 8, 6, 9,
       2, 9, 9, 3, 2, 9, 0, 8, 3, 1, 3, 5, 6, 7, 6, 6, 4, 5, 8, 0, 5, 4,
       5, 3, 7, 0, 7, 7, 0, 9, 2, 6, 4, 5, 9, 9, 7, 4, 1, 0, 2, 2, 6, 2,
       7, 7, 9, 3, 2, 9, 6, 6, 3, 5, 2, 9, 5, 9, 8, 7, 9, 3, 7, 1, 7, 7,
       0, 4, 9, 2, 5, 7, 0, 0, 6, 4, 1, 6, 6, 4, 7, 5, 2, 5, 6, 8, 3, 2,
       2, 6, 7, 9, 7, 2, 2, 7, 6, 2, 9, 5, 1, 3, 1, 8, 6, 1, 7, 3, 0, 8,
       4, 2, 6, 4, 2, 2, 4, 3, 2, 4, 9, 5, 7, 8, 6,

In [23]:
sum(y_predict == y_test) / len(y_test)

0.9888579387186629

In [24]:
from playML.metrics import accuracy_score

In [25]:
accuracy_score(y_test, y_predict)

0.9888579387186629

In [26]:
my_knn_clf.score(X_test, y_test)

0.9888579387186629

# scikit-learn中的accuracy_score

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [31]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [32]:
y_predict = knn_clf.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy_score(y_test, y_predict)

0.9888888888888889

In [36]:
knn_clf.score(X_test, y_test)

0.9888888888888889

# 超参数问题

超参数: 在算法运行前需要确定的参数<br>
模型参数: 算法过程中学习的参数

# 寻找最好的k

In [37]:
best_score = 0.0
best_k = -1
for k in range(1, 11):
    knn_clf = KNeighborsClassifier(n_neighbors=k)
    knn_clf.fit(X_train, y_train)
    score = knn_clf.score(X_test, y_test)
    if score > best_score:
        best_k = k
        best_score = score
        
print("best_k=", best_k, " best_Score=", best_score)

best_k= 4  best_Score= 0.9916666666666667


考虑了距离权重后的knn(用倒数来得)
![weight](weightKNN.png)

# 是使用distance 还是不用距离

In [38]:
best_method = ""
best_score = 0.0
best_k = -1
for method in ["uniform", "distance"]:
    for k in range(1, 11):
        knn_clf = KNeighborsClassifier(n_neighbors=k)
        knn_clf.fit(X_train, y_train)
        score = knn_clf.score(X_test, y_test)
        if score > best_score:
            best_k = k
            best_score = score
            best_method = method
        
print("best_k=", best_k, " best_Score=", best_score, " bestmethod:", best_method)

best_k= 4  best_Score= 0.9916666666666667  bestmethod: uniform


# 还有很多种距离
比如曼哈顿距离 这要是一种参数
![dist](distances.png)
# 搜索最好的p

In [40]:
%%time

best_method = ""
best_score = 0.0
best_k = -1
best_p = -1
for method in ["uniform", "distance"]:
    for k in range(1, 11):
        for p in range(1, 4):
            knn_clf = KNeighborsClassifier(n_neighbors=k, weights=method, p=p)
            knn_clf.fit(X_train, y_train)
            score = knn_clf.score(X_test, y_test)
            if score > best_score:
                best_k = k
                best_score = score
                best_method = method
                best_p = p
        
print("best_k=", best_k, " best_Score=", best_score, " bestmethod:", best_method, " best_p=", best_p)

best_k= 4  best_Score= 0.9916666666666667  bestmethod: uniform  best_p= 2
Wall time: 15.6 s


In [ ]:
# 上面可以看出来有很多超参数可以选择 那么我们怎么来做呢? 实际上这是一种网格搜索 sklearn中为我们封装