# numpy array 基础

In [ ]:
import numpy as np
print(np.__version__)

1.14.3


## python list 特点

In [2]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L[3]

3

In [ ]:
import array
arr = array.array('i', [i for i in range(10)])

In [ ]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np array

In [7]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
nparr[5]

5

In [ ]:
nparr.dtype

dtype('int32')

In [10]:
nparr[7] = 3.5

In [11]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 3, 8, 9])

In [12]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

## other methods to create array

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10).dtype

dtype('float64')

In [15]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange(startIncluded, endExcluded, step)

In [21]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace(startIncluded, endIncluded, totalPoints) 

In [25]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [26]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### np.random

In [27]:
np.random.randint(0, 10, 5)

array([7, 1, 6, 8, 5])

In [28]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.random.randint(4,8,size=10)

array([5, 7, 4, 6, 4, 4, 6, 6, 7, 6])

In [30]:
np.random.randint(4,8,size=(3,5))

array([[7, 6, 6, 4, 6],
       [6, 6, 7, 6, 6],
       [5, 5, 4, 6, 7]])

In [33]:
np.random.seed(666)
print(np.random.randint(4,8,size=5))
np.random.seed(666)
print(np.random.randint(4,8,size=5))

[4 6 5 6 6]
[4 6 5 6 6]


In [34]:
np.random.random()

0.12897684222354033

In [35]:
np.random.random(10)

array([0.75033054, 0.33596835, 0.24434285, 0.25987554, 0.28116849,
       0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625])

In [36]:
np.random.random((3, 5))

array([[0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ],
       [0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949]])

# normal dist random

In [37]:
np.random.normal(10, 100)

-15.584759282610502

In [38]:
# .normal(均值, 方差, size)
np.random.normal(0, 1, (3, 5))

array([[-1.76438083, -0.94249688, -1.58045861,  0.90472662, -0.82628327],
       [ 0.82101369,  0.36712592,  1.65399586,  0.13946473, -1.21715355],
       [-0.99494737, -1.56448586, -1.62879004,  1.23174866, -0.91360034]])

In [39]:
# 查看帮助文档
np.random.normal?

In [ ]:
import numpy as np
np.random.normal(0, 100, (6,6))

array([[-186.04922548,   32.93166046,  -18.88382031, -114.31399899,
        -158.23594766,   15.35993543],
       [ -22.13467926,   93.51025343,   -3.46461623,  -57.34050223,
         -74.02511011, -112.86740743],
       [ -27.0949876 ,  -41.78494126,  118.89343915,  -17.65724386,
         106.8274101 ,   68.02456861],
       [ -91.0809927 ,  -13.18581904, -150.42228048,   17.19527858,
         113.16780079,   54.24602489],
       [  24.43613447,  -50.86796705,   46.6063779 ,   34.3953818 ,
         -88.77641017,  -93.33780186],
       [ -16.94715312,  142.22159018,  108.49975654,  -54.22036364,
        -170.65769288,  138.03993576]])