# numpy array 基础

In [1]:
import numpy as np
print(np.__version__)

1.15.1


## python list 特点

In [2]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L[3]

3

In [4]:
import array
arr = array.array('i', [i for i in range(10)])

In [5]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np array

In [6]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
nparr[5]

5

In [8]:
nparr.dtype

dtype('int64')

In [9]:
nparr[7] = 3.5

In [10]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 3, 8, 9])

In [11]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

## other methods to create array

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10).dtype

dtype('float64')

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arange(startIncluded, endExcluded, step)

In [19]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [20]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace(startIncluded, endIncluded, totalPoints) 

In [23]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### np.random

In [25]:
np.random.randint(0, 10, 5)

array([6, 9, 5, 6, 7])

In [26]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.random.randint(4,8,size=10)

array([5, 7, 7, 6, 4, 5, 5, 4, 7, 6])

In [28]:
np.random.randint(4,8,size=(3,5))

array([[6, 4, 7, 5, 6],
       [5, 6, 4, 7, 7],
       [6, 5, 7, 6, 7]])

In [29]:
np.random.seed(666)
print(np.random.randint(4,8,size=5))
np.random.seed(666)
print(np.random.randint(4,8,size=5))

[4 6 5 6 6]
[4 6 5 6 6]


In [30]:
np.random.random()

0.12897684222354033

In [31]:
np.random.random(10)

array([0.75033054, 0.33596835, 0.24434285, 0.25987554, 0.28116849,
       0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625])

In [32]:
np.random.random((3, 5))

array([[0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ],
       [0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949]])

# normal dist random

In [33]:
np.random.normal(10, 100)

-15.584759282610502

In [34]:
# .normal(均值, 方差, size)
np.random.normal(0, 1, (3, 5))

array([[-1.76438083, -0.94249688, -1.58045861,  0.90472662, -0.82628327],
       [ 0.82101369,  0.36712592,  1.65399586,  0.13946473, -1.21715355],
       [-0.99494737, -1.56448586, -1.62879004,  1.23174866, -0.91360034]])

In [35]:
# 查看帮助文档
np.random.normal?

In [36]:
import numpy as np
np.random.normal(0, 100, (6,6))

array([[ -27.08440668,  142.02491357,  -98.22643888,   80.97649843,
         185.20522659,  167.81902109],
       [ -98.07692372,   47.03108236,   18.22699079,  -84.38824922,
          20.99683302,   22.95866621],
       [  26.3076422 ,  216.63322225, -104.88759251, -184.76844229,
          53.4015028 , -119.57480238],
       [ -28.91573716,  -24.33270341,  -74.26665273,  120.79051056,
         102.78771143,    5.73881974],
       [-156.00397611,  -30.40116113, -119.84359191,  -87.18349948,
          17.65971815,  -20.26336417],
       [  96.70290756, -193.16961713,  -19.85466195,  125.30885252,
          30.48324273, -142.91781382]])

# fancy indexing in np

In [37]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
x[3]

3

In [39]:
x[3:8]

array([3, 4, 5, 6, 7])

In [40]:
x[3:9:2]

array([3, 5, 7])

In [41]:
# 不是等步长
[x[3], x[5], x[8]]

[3, 5, 8]

In [42]:
ind = [3, 5, 8]

In [43]:
# 这就是fancy indexing  索引是1维数组
x[ind]

array([3, 5, 8])

In [44]:
# 索引数组是二维数组
ind = np.array([[0,2], [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [45]:
X = x.reshape(4, -1)

In [46]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row, col]

array([ 1,  6, 11])

In [48]:
X[0, col]

array([1, 2, 3])

In [49]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

# np.array 比较

In [50]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [52]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [53]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [54]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [55]:
np.sum(x <= 3)

4

In [56]:
np.count_nonzero(x <= 3)

4

In [57]:
np.any(x == 0)

True

In [58]:
np.all(x > 0)

False

In [59]:
np.all(x>=0)

True

In [60]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.sum(X % 2 == 0)

8

In [62]:
np.sum(X % 2 == 0, axis = 1)

array([2, 2, 2, 2])

In [63]:
np.sum(X%2 == 0, axis = 0)

array([4, 0, 4, 0])

In [64]:
# 注意这里是位运算 不是条件运算符
np.sum((x > 3) & (x < 10))

6

In [65]:
np.sum(~(x==0))

15

In [66]:
x[x<5]

array([0, 1, 2, 3, 4])

In [67]:
X[X%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [68]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
X[X[:,3] %3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
# pandas 中的DataFrame