这个全都是Tensorflow 示例学习课程中的代码 https://www.bilibili.com/video/av26835020/

第一部分是tf的基础运行单元Variable

In [1]:
import tensorflow as tf
a = 3
# 1行2列
w = tf.Variable([[0.5, 1.0]])

# 2列1行
x = tf.Variable([[2.0], [1.0]])

# 这里实际上并没有开始计算
y = tf.matmul(w,x)


print(w)

init_op=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(y)
    
    # eval会进行运算
    print(y.eval())
                 
                 

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32_ref>
Tensor("MatMul:0", shape=(1, 1), dtype=float32)
[[2.]]


看完了 https://www.bilibili.com/video/av26835020/?p=3

In [3]:
#float32 更好用
# [[0,0,0,0],[0,0,0,0],[0,0,0,0]]

tf.zeros([3,4])
# all is 1
tf.ones([3,4])
tensor1 = tf.Variable([[1,2],[3,4],[5,6]])


with tf.Session() as sess:
    sess.run(init_op)
    # 生成全0的3行4列的矩阵
    print("zeros", tf.zeros([3,4]).eval())
    print("ones", tf.ones([3,4]).eval())
    # 按照某个tensor 的大小来生成
    print("ones_like", tf.ones_like(tensor1).eval())
    print("zeros_like", tf.zeros_like(tensor1).eval())
    
    # 生成1维的tensor 通过list
    print("1D tensor", tf.constant([1,2,3,4,5,6]).eval())
    
    #生成2D的tensor根据常量值-1
    print("2D tensor with -1", tf.constant(-1, shape=[2,3]).eval())
    
    # 从第一个数开始 到第二个数结束 创建制定数量个数的数字
    # [10.       10.333333 10.666667 11.       11.333333 11.666667 12.      ]
    print("linespace", tf.linspace(10.0, 12.0, 7, name="linspace").eval())
    start = 3
    delta = 4
    limit = 18
    print("range", tf.range(start, limit, delta).eval())
   

zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
ones_like [[1 1]
 [1 1]
 [1 1]]
zeros_like [[0 0]
 [0 0]
 [0 0]]
1D tensor [1 2 3 4 5 6]
2D tensor with -1 [[-1 -1 -1]
 [-1 -1 -1]]
linespace [10.       10.333333 10.666667 11.       11.333333 11.666667 12.      ]
range [ 3  7 11 15]


In [5]:
# 随机值
with tf.Session() as s:
    print("高斯分布", tf.random_normal([2,3], mean=-1, stddev=4).eval())
    
    # 打乱
    c = tf.constant([[1,2], [3,4], [5,6]])
    shuf = tf.random_shuffle(c)
    print("shuffle", shuf.eval())

高斯分布 [[-0.11718267  1.5525973   0.41056156]
 [-6.031634    4.6220355   3.7141514 ]]
shuffle [[3 4]
 [1 2]
 [5 6]]


In [9]:
# 一个从0 开始打印
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

with tf.Session() as s:
    #        global_variables_initializer
    s.run(tf.global_variables_initializer())
    print("Entering....")
    print(s.run(state))
    for _ in range(3):
        print("entring for...")
        s.run(update)
        print(s.run(state))

Entering....
0
entring for...
1
entring for...
2
entring for...
3
