# 一个最基础的神经元RELU函数
![relu](img/relu.png)

## Recitified Linear Unit 修正线性单元
![nn](img/nn1.png)
![nn](img/nn2.png)

# 课程中的记号
![nn](img/nn3.png)
![nn](img/nn4.png)
![nn](img/nn5.png)
![nn](img/nn6.png)


# broadcasting
![img](img/nn7.png)

In [1]:
import numpy as np

In [2]:
A = np.array([[56.0, 0, 4.4, 68], 
              [1.2, 104, 52, 8.0],
              [1.8, 135, 99.0, 0.9]])

In [3]:
A.shape

(3, 4)

In [4]:
cal = np.sum(A, axis=0)

In [5]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [6]:
precent = 100 * A / cal.reshape(1, 4)

In [7]:
precent

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

# axis
![axis](img/nn8.png)

# more examples
![imh](img/nn9.png)

# 避免犯错的一些技巧

In [8]:
# Note 1: 避免(5,)  这样的array
# 而是(5,1)这样的向量
a = np.random.randn(5)

In [9]:
a

array([ 0.06229796, -1.67111383, -0.83837956, -0.81441442, -2.39369578])

In [10]:
a.shape

(5,)

In [11]:
print(a.T)

[ 0.06229796 -1.67111383 -0.83837956 -0.81441442 -2.39369578]


In [12]:
print(np.dot(a, a.T))

9.892433076671622


In [15]:
#实际上我们用矩阵的话就能减少犯错
A = a.reshape((1,5))

In [16]:
A

array([[ 0.06229796, -1.67111383, -0.83837956, -0.81441442, -2.39369578]])

In [17]:
print(A.T)

[[ 0.06229796]
 [-1.67111383]
 [-0.83837956]
 [-0.81441442]
 [-2.39369578]]


In [18]:
print(np.dot(A, A.T))

[[9.89243308]]


In [19]:
print(np.dot(A.T, A))

[[ 3.88103607e-03 -1.04106986e-01 -5.22293379e-02 -5.07363584e-02
  -1.49122369e-01]
 [-1.04106986e-01  2.79262142e+00  1.40102767e+00  1.36097919e+00
   4.00013811e+00]
 [-5.22293379e-02  1.40102767e+00  7.02880285e-01  6.82788400e-01
   2.00682561e+00]
 [-5.07363584e-02  1.36097919e+00  6.82788400e-01  6.63270844e-01
   1.94946036e+00]
 [-1.49122369e-01  4.00013811e+00  2.00682561e+00  1.94946036e+00
   5.72977949e+00]]


In [20]:
b = np.random.randn(5,1)
print(b)

[[-0.12559416]
 [-0.07512304]
 [-0.9145903 ]
 [-1.37720234]
 [ 0.11685337]]


In [22]:
# Note 2: 多用assert
assert(b.shape == (5,1))

# more on logic reg cost func
![img](img/nn10.png)<br>
then we use a log<br>
log(xxxxx) = -L(xxxx)<br>
用负号是因为我们要最大化这个概率, 但是是最小化损失函数<br>
# 多个数据时<br>
我们要最大化:p1*p2*p3....*pm<br>
这个取log和负号后就是跟我们看到的一样了.<br>